apache/qpid-broker-j

- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/firewall/AbstractFirewallRuleImpl.java
- broker-plugins/access-control/src/test/java/org/apache/qpid/server/security/access/firewall/HostnameFirewallRuleTest.java
- broker-plugins/access-control/src/test/java/org/apache/qpid/server/security/access/firewall/NetworkFirewallRuleTest.java
This PR is supposed to solve issue described in JIRA [QPID-8578](https://issues.apache.org/jira/browse/QPID-8578).
> QPID-8578: [Broker-J] ACL firewall predicates should be applied to HTTP(S) connections

- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/util/Any.java
- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/util/Empty.java
- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/util/PrefixTreeSet.java
- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/util/WildCardSet.java
- broker-plugins/access-control/src/test/java/org/apache/qpid/server/security/access/plugins/RuleOutcomeTest.java
Missing license headers were added in broker-plugins/access-control module
> NO-JIRA: Added missing license headers

- apache-qpid-broker-j/src/main/assembly/bin.xml
- pom.xml
This PR addresses [QPID-8584](https://issues.apache.org/jira/browse/QPID-8584), removing compilation warning "unknown enum constant com.google.j2objc.annotations.ReflectionSupport.Level.FULL"
> QPID-8584: [Broker-J] Compile warning unknown enum constant com.google.j2objc.annotations.ReflectionSupport.Level.FULL

- perftests/pom.xml
- pom.xml
This PR addresses [QPID-8586](https://issues.apache.org/jira/browse/QPID-8586), adding nashorn dependency to perftests module to make it compatible with java 17
> QPID-8586: [Broker-J] Nashorn script engine dependency for java 11/17 compatibility

- broker-core/src/main/java/org/apache/qpid/server/queue/FlowToDiskOverflowPolicyHandler.java
- broker-core/src/test/java/org/apache/qpid/server/queue/FlowToDiskOverflowPolicyHandlerTest.java
This PR addresses JIRA QPID-8590 to improve flow-to-disk mechanism: messages should be flowed to disk when their amount exceeds overflow limit or restored in memory when their amount is less than overflow limit. Although performance of purging messages from queue ( cleanQueue() operation ) is increased.
> QPID-8590: [Broker-J] Purge on flow to disk queue

- broker-core/src/main/java/org/apache/qpid/server/exchange/AbstractExchange.java
- broker-core/src/test/java/org/apache/qpid/server/exchange/TopicExchangeTest.java
This PR addresses issue [QPID-8572](https://issues.apache.org/jira/browse/QPID-8572) adding a fix and new unit test.
> QPID-8572: [Broker-J] The binding is broken when queue and exchange have the same name

- broker-plugins/management-http/src/main/java/org/apache/qpid/server/management/plugin/HttpManagement.java
- broker-plugins/websocket/src/main/java/org/apache/qpid/server/transport/websocket/WebSocketProvider.java
This PR addresses issue [QPID-8585](https://issues.apache.org/jira/browse/QPID-8585), replacing deprecated methods in management-http and websocket plugins
> QPID-8585: [Broker-J] Deprecated methods in management-http / websocket plugin

- broker-core/src/main/java/org/apache/qpid/server/model/port/AmqpPort.java
- broker-core/src/test/java/org/apache/qpid/server/transport/SNITest.java
- qpid-test-utils/src/main/java/org/apache/qpid/test/utils/JvmVersion.java
This PR affects [QPID-8597](https://issues.apache.org/jira/browse/QPID-8587) fixing unit tests for java 17 compatibility
> QPID-8597: [Broker-J] SNI hostname handling for java 11/17 compatibility

- broker-core/src/main/java/org/apache/qpid/server/virtualhost/AbstractVirtualHost.java
- broker-core/src/test/java/org/apache/qpid/server/virtualhost/VirtualHostInitialConfigurationTest.java
This PR addresses [QPID-8588](https://issues.apache.org/jira/browse/QPID-8588), fixing an NPE in AbstractVirtualHost
> QPID-8588: [Broker-J] NullPointerException in AbstractVirtualHost.autoCreateNode

- broker-instrumentation/README.md
- broker-instrumentation/pom.xml
- broker/pom.xml
- doc/java-broker/src/docbkx/runtime/Java-Broker-Runtime-Instrumentation.xml
- pom.xml
The broker instrumentation module has been renamed to match the other modules naming.
```
broker-instrumentation -> qpid-broker-instrumentation
```
Added examples with list of classes to instrument to Java Broker book.
> QPID-8601: [Broker-J] Renamed module and updated documentation

- broker-core/src/main/java/org/apache/qpid/server/model/Broker.java
- broker-plugins/query-engine/pom.xml
- doc/developer-guide/src/main/markdown/build-instructions.md
- doc/developer-guide/src/main/markdown/quick-start.md
- doc/developer-guide/src/main/markdown/release-instructions.md
- doc/java-broker/src/docbkx/Java-Broker-Appendix-Miscellaneous.xml
- doc/java-broker/src/docbkx/Java-Broker-Getting-Started.xml
- doc/java-broker/src/docbkx/Java-Broker-Installation.xml
- doc/java-broker/src/docbkx/Java-Broker-Introduction.xml
- doc/java-broker/src/docbkx/runtime/Java-Broker-Runtime-Memory.xml
The minimum Java version has been increased to Java 11 in the documentation.
> QPID-8596: [Broker-J] Replaced Java 1.8 by Java 11 in the documentation

- broker-plugins/jdbc-logging-logback/pom.xml
- pom.xml
**Updated dependencies**
logback 1.2.11
logback-db 1.2.11.1 (before version 1.2.8 it was part of logback-core)
guava 31.1-jre
jackson 2.13.4
jackson-databind 2.13.4.2
jetty 9.49.v20220914
bonecp 0.8.0.RELEASE
commons-cli 1.5.0
asm 9.4
dojo 1.17.2
dgrid 1.3.3
mockito 4.8.1
netty 4.1.8.Final
maven-core 3.8.6
maven-resolver 1.8.2
nashorn 15.4
~~apache-directory 2.0.0.AM26~~ (there is a bug in 2.0.0.AM26 that prevents building on Java 17 - details [DIRSERVER-2326](https://issues.apache.org/jira/browse/DIRSERVER-2326))
kerby 2.0.2
bouncy-castle - 1.70
> QPID-8580: [Broker-J] Updated dependencies

- apache-qpid-broker-j/pom.xml
- doc/pom.xml
There is an issue with GNU tar long file mode in some OSes. 
`group id '1377585961' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit`
Changing the mode to 'posix' fixes the issue.
> NO-JIRA: Replaced gnu by posix in tar long file mode (assembly-plugin)

- pom.xml
- systests/end-to-end-conversion-tests/pom.xml
`maven-core` contains old version of `maven-resolver` libraries (1.6.3) which broke the execution of `end-to-end-conversion-tests` module.
> QPID-8580: [Broker-J] Fixed maven-resolver version conflict

- apache-qpid-broker-j/pom.xml
- doc/pom.xml
Reverts apache/qpid-broker-j#159
There is an issue with 7-zip on Windows (Midnight Commander in Ubuntu 22.04 has the same issues), which truncates path to 100 characters in `posix` tar long file mode of maven-assembly-plugin. Unpacking by `tar -xvf` works without any issues.
Reverting change for wider compatibility. Downside is that build/release will fail on OSes where user id is larger than 2097151.
Details:
https://www.gnu.org/software/tar/manual/html_chapter/Formats.html
https://sourceforge.net/p/sevenzip/bugs/2228/
https://issues.onehippo.com/browse/ARCHE-565?attachmentViewMode=list
> Revert "NO-JIRA: Replaced gnu by posix in tar long file mode (assembly-plugin)"

- apache-qpid-broker-j/src/main/assembly/dependency-verification/DEPENDENCIES_REFERENCE
- perftests/src/main/assembly/dependency-verification/DEPENDENCIES_REFERENCE
- pom.xml
- qpid-test-utils/pom.xml
This PR updates 
- com.fasterxml.jackson.core:jackson-core to 2.14.1
- com.fasterxml.jackson.core:jackson-databind to 2.14.1 
- org.apache.qpid:qpid-client to 6.4.0
- org.bouncycastle:bcprov-jdk15on to org.bouncycastle:bcprov-jdk18on:1.72
- org.bouncycastle:bcpkix-jdk15on to org.bouncycastle:bcpkix-jdk18on:1.72
- org.dojotoolkit:dojo to 1.17.3
- org.junit.jupiter.* to 5.9.2
- org.mockito:mockito-core to 5.0.0
- io.netty:* to 4.1.87.Final
> NO-JIRA: update dependencies versions

- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/config/RuleBasedAccessControl.java
- broker-plugins/access-control/src/main/java/org/apache/qpid/server/security/access/plugins/AclFileAccessControlProviderImpl.java
- broker-plugins/graylog-logging-logback/src/test/java/org/apache/qpid/server/logging/logback/validator/TestConfiguredObjectFactory.java
- broker-plugins/graylog-logging-logback/src/test/java/org/apache/qpid/server/logging/logback/validator/TestConfiguredObjectTypeFactory.java
This PR addresses JIRA [QPID-8653](https://issues.apache.org/jira/browse/QPID-8653), refactoring code in module broker-plugins/access-control
> QPID-8653: [Broker-J] Code cleanup: access-control - collection type arguments, collection factory methods, lambdas

- apache-qpid-broker-j/src/main/assembly/dependency-verification/DEPENDENCIES_REFERENCE
- perftests/src/main/assembly/dependency-verification/DEPENDENCIES_REFERENCE
- pom.xml
- systests/qpid-systests-http-management/src/test/java/org/apache/qpid/tests/http/authentication/SaslTest.java
This PR addresses [QPID-8655](https://issues.apache.org/jira/browse/QPID-8655), updating broker dependencies.
Following dependencies are updated:
**runtime dependencies**
com.fasterxml.jackson.core:jackson-core 2.15.2 => 2.15.3
com.fasterxml.jackson.core:jackson-databind 2.15.2 => 2.15.3
com.google.guava:guava 32.1.2-jre => 32.1.3-jre
org.eclipse.jetty:jetty-server 11.0.15 => 11.0.18
org.eclipse.jetty:jetty-servlet 11.0.15 => 11.0.18
org.eclipse.jetty:jetty-servlets 11.0.15 => 11.0.18
org.eclipse.jetty:jetty-rewrite 11.0.15 => 11.0.18
org.eclipse.jetty.websocket:websocket-jetty-server 11.0.15 => 11.0.18
org.ow2.asm:asm 9.5 => 9.6
org.ow2.asm:asm-tree 9.5 => 9.6
org.slf4:slf4j-api 2.0.7 => 2.0.9
**test dependencies**
com.h2database:h2 1.4.220 => 2.1.224
io.netty:netty-buffer 4.1.96.Final …
> QPID-8655: [Broker-J] Dependency updates for version 9.1.x

- broker-core/src/main/java/org/apache/qpid/server/model/BrokerModel.java
- broker-core/src/main/java/org/apache/qpid/server/store/AbstractConfigurationStoreUpgraderAndRecoverer.java
- broker-core/src/main/java/org/apache/qpid/server/store/BrokerStoreUpgraderAndRecoverer.java
- broker-core/src/main/java/org/apache/qpid/server/store/UpgraderHelper.java
- broker-core/src/main/java/org/apache/qpid/server/store/VirtualHostStoreUpgraderAndRecoverer.java
- broker-core/src/test/java/org/apache/qpid/server/store/BrokerStoreUpgraderAndRecovererTest.java
- broker-core/src/test/java/org/apache/qpid/server/store/VirtualHostStoreUpgraderAndRecovererTest.java
This PR is a follow-up to the [PR 235](https://github.com/apache/qpid-broker-j/pull/235) and addresses JIRA [QPID-8666](https://issues.apache.org/jira/browse/QPID-8666), adding upgrading the broker model version from 9.0 to 9.1
> QPID-8666: [Broker-J] Broker plugin jdbc-provider-bone replacement

- .github/workflows/build.yml
This PR updates github actions cache / checkout / setup-java to version 4
> NO-JIRA: Update cache, checkout and setup-java github actions to version 4

- qpid-docker/entrypoint.sh
The configuration of queues happens in `./work-override/default/config/default.json`, so it needs to copy them recursively, right?
> QPID-8679: [Broker-J] Copy nested configuration files in work-init and work-override

- .github/workflows/build.yml
This PR updates github actions "upload-artifact" to version 4
> NO-JIRA - Update upload-artifact github actions to version 4

- broker-core/src/main/java/org/apache/qpid/server/model/Producer.java
- broker-core/src/main/java/org/apache/qpid/server/model/ProducerImpl.java
- broker-plugins/amqp-1-0-protocol/src/main/java/org/apache/qpid/server/protocol/v1_0/StandardReceivingLinkEndpoint.java
Sets the destination ID for the DELAYED_DELIVERY producer to allow opening the destination for DELAYED_DELIVERY producers when the user double-clicks on a producer in the broker's GUI.
> QPID-8683: [Broker-J] Set destination ID for DELAYED_DELIVERY producer
